import type { GTFSStop, GTFSRoute } from "./types";

// These JSON files are generated by scripts/build-gtfs.ts at build time
// and served from /gtfs/stops.json and /gtfs/routes.json

let stopsCache: GTFSStop[] | null = null;
let routesCache: Map<string, GTFSRoute> | null = null;
let stopsByIdCache: Map<string, GTFSStop> | null = null;

export async function loadStops(): Promise<GTFSStop[]> {
  if (stopsCache) return stopsCache;
  const res = await fetch("/gtfs/stops.json");
  if (!res.ok) throw new Error("Failed to load stops.json");
  stopsCache = (await res.json()) as GTFSStop[];
  return stopsCache;
}

export async function loadRoutesMap(): Promise<Map<string, GTFSRoute>> {
  if (routesCache) return routesCache;
  const res = await fetch("/gtfs/routes.json");
  if (!res.ok) throw new Error("Failed to load routes.json");
  const routes = (await res.json()) as GTFSRoute[];
  routesCache = new Map(routes.map((r) => [r.id, r]));
  return routesCache;
}

export async function loadStopsByIdMap(): Promise<Map<string, GTFSStop>> {
  if (stopsByIdCache) return stopsByIdCache;
  const stops = await loadStops();
  stopsByIdCache = new Map(stops.map((s) => [s.id, s]));
  return stopsByIdCache;
}

export async function getStopById(stopId: string): Promise<GTFSStop | null> {
  const map = await loadStopsByIdMap();
  return map.get(stopId) ?? null;
}

// TransLink SEQ uses route_ids with a delimiter (e.g. "RPSP-3962")
// The realtime feed's route_id may include a calendar suffix after '-'
// We normalize by taking the part before the first '-' for lookup
export function normalizeRouteId(routeId: string, routesMap: Map<string, GTFSRoute>): string {
  if (routesMap.has(routeId)) return routeId;
  const base = routeId.split("-")[0];
  // Try to find a route whose id starts with the base
  for (const [id] of routesMap) {
    if (id === base || id.startsWith(base + "-")) return id;
  }
  return routeId;
}

export function getRouteColor(route: GTFSRoute | undefined): string {
  if (!route || !route.color) return "#525252";
  return `#${route.color}`;
}

export function getRouteTextColor(route: GTFSRoute | undefined): string {
  if (!route || !route.textColor) return "#ffffff";
  return `#${route.textColor}`;
}
